src/GregGoldsmith.FlashParking.Web/Models/Home/ParkingLotListModel.cs
using GregGoldsmith.FlashParking.Application.Dto;
using GregGoldsmith.FlashParking.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GregGoldsmith.FlashParking.Web.Models.Home
{
    public class ParkingLotListModel
    {
        public IReadOnlyList<ParkingLotDto> ParkingLots { get; }

        public ParkingLotListModel(IReadOnlyList<ParkingLotDto> parkingLots)
        {
            ParkingLots = parkingLots;
        }

        public string GetBadgeClass(int availableSpaces)
        {
            if (availableSpaces == 0)
                return "bg-danger";
            else
                return "bg-success";
        }
    }
}

src/GregGoldsmith.FlashParking.Web/Controllers/HomeController.cs
using GregGoldsmith.FlashParking.Application;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using GregGoldsmith.FlashParking.Web.Models.Home;
using System;
using System.Collections.Generic;
using GregGoldsmith.FlashParking.Application.Dto;

namespace GregGoldsmith.FlashParking.Web.Controllers
{
    [Route("[controller]")]
    [Route("")]
    public class HomeController : FlashParkingControllerBase
    {
        private readonly IParkingLotAppService _parkingLotAppService;

        public HomeController(IParkingLotAppService parkingLotAppService)
        {
            _parkingLotAppService = parkingLotAppService;
        }

        [HttpGet]  // GET /Home
        public async Task<ActionResult> Index()
        {
            try
            {
                Alerts.Success(L("WelcomeAlertMessage"), L("WelcomeAlertTitle"));
                ViewBag.Title = L("HomeTitle");
                var output = await _parkingLotAppService.GetAll();
                if (output == null || output.Count == 0)
                {
                    Alerts.Warning("NoParkingLotsMessage", "NoParkingLotsTitle");
                    return View(new ParkingLotListModel(new List<ParkingLotDto>()));
                }
                else
                {
                    var model = new ParkingLotListModel(output);
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                this.Logger.Error(ex.ToString());
                Alerts.Danger("ErrorAlertMessage", "ErrorAlertTitle");
                return new ObjectResult(ex);
            }
        }
    }
}

src/GregGoldsmith.FlashParking.Web/Controllers/ParkingLotController.cs
using GregGoldsmith.FlashParking.Application;
using GregGoldsmith.FlashParking.Application.Dto;
using GregGoldsmith.FlashParking.Web.Models.ParkingLot;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using System;
using System.Threading.Tasks;

namespace GregGoldsmith.FlashParking.Web.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class ParkingLotController : FlashParkingControllerBase
    {
        private IParkingLotAppService _parkingLotAppService;

        public ParkingLotController(IParkingLotAppService parkingLotAppService)
        {
            _parkingLotAppService = parkingLotAppService;
        }

        [HttpGet]
        [Route("Index")]
        public async Task<ActionResult> Index(int parkingLotId)
        {
            try
            {
                ViewBag.Title = L("ParkingLotTitle");
                ParkingLotDto output = await _parkingLotAppService.Get(parkingLotId);
                if (output == null)
                {
                    Alerts.Warning("NoParkingLotsMessage", "NoParkingLotsTitle");
                    return View(new ParkingLotModel(new ParkingLotDto()));
                }
                else
                {
                    var model = new ParkingLotModel(output);
                    return View(model);
                }
            }
            catch (Exception ex)
            {
                this.Logger.Error(ex.ToString());
                Alerts.Danger("ErrorAlertMessage", "ErrorAlertTitle");
                return View(new ParkingLotModel(new ParkingLotDto()));
            }
        }

        [HttpPost]
        [Route("GetParkingLot")]
        public async Task<IActionResult> GetParkingLot([FromBody] int id)
        {
            try
            {
                ParkingLotModel result = new ParkingLotModel(new ParkingLotDto());
                ParkingLotDto output = await _parkingLotAppService.Get(id);

                if (output == null)
                {
                    Alerts.Warning("NoParkingLotsMessage", "NoParkingLotsTitle");
                    return NotFound();
                }
                else
                {
                    var model = new ParkingLotModel(output);
                    return Json(model, new JsonSerializerSettings { ContractResolver = new DefaultContractResolver() });
                }
            }
            catch (Exception ex)
            {
                this.Logger.Error(ex.ToString());
                Alerts.Danger("ErrorAlertMessage", "ErrorAlertTitle");
                return new ObjectResult(ex);
            }
        }

        [HttpPost]
        [Route("Park")]
        public async Task<IActionResult> Park([FromBody] ParkModel parkModel)
        {
            try
            {
                await _parkingLotAppService.Park(new ParkDto(parkModel.ParkingLot, parkModel.Vehicle));

                return Json(true, new JsonSerializerSettings { ContractResolver = new DefaultContractResolver() });
            }
            catch (Exception ex)
            {
                this.Logger.Error(ex.ToString());
                Alerts.Danger("ErrorAlertMessage", "ErrorAlertTitle");
                return new ObjectResult(ex);
            }
        }

        [HttpPost]
        [Route("Leave")]
        public async Task<IActionResult> Leave([FromBody] LeaveModel leaveModel)
        {
            try
            {
                await _parkingLotAppService.Leave(leaveModel.ParkingLot, leaveModel.VehicleId);

                return Json(true, new JsonSerializerSettings { ContractResolver = new DefaultContractResolver() });
            }
            catch (Exception ex)
            {
                this.Logger.Error(ex.ToString());
                Alerts.Danger("ErrorAlertMessage", "ErrorAlertTitle");
                return new ObjectResult(ex);
            }
        }
    }
}

src/GregGoldsmith.FlashParking.Web/Views/Home/Index.cshtml
@model GregGoldsmith.FlashParking.Web.Models.Home.ParkingLotListModel
@using GregGoldsmith.FlashParking.Web.Startup
@{ ViewBag.ActiveMenu = PageNames.Home; }

@section scripts
{
    <environment names="Development">
        <script src="~/js/views/home/parkinglots.js"></script>

    </environment>

    <environment names="Staging,Production">
        <script src="~/js/views/home/parkinglots.min.js"></script>
    </environment>
}

@foreach (var parkingLot in Model.ParkingLots)
{
<div class="card mb-5 shadow">
    <div class="card-header bg-info text-white">
        <ul class="list-group">
            <li class="border-0 list-group-item bg-info text-white d-flex justify-content-between align-items-center">
                <h3> @parkingLot.Name </h3>
                <h5 class=""><span class="fw-light p-3 badge @Model.GetBadgeClass(parkingLot.AvailableParkingSpaces)">@(parkingLot.AvailableParkingSpaces == 0 ? "Lot Full" : "Spaces Available")</span></h5>
            </li>
        </ul>
    </div>
    <div class="card-body mx-3">
        <h5><span class="text-black">@parkingLot.Address</span></h5>
        <div class="ml-auto bg-light">
            <ul class="list-group">
                <li class="list-group-item list-group-item-action">
                    @L("NumberOfSpaces")
                    <span class="badge rounded-pill bg-dark text-white"> @parkingLot.NumberOfParkingSpaces</span>
                </li>
                <li class="list-group-item list-group-item-action">
                    @L("AvailableSpaces")
                    <span class="badge rounded-pill text-white @Model.GetBadgeClass(parkingLot.AvailableParkingSpaces)"> @parkingLot.AvailableParkingSpaces</span>
                </li>
            </ul>
        </div>
        <div class="mt-3 d-grid gap-2">
            @Html.ActionLink("Park Here", "Index", "ParkingLot", new { ParkingLotId = parkingLot.Id }, new { @class = "btn btn-primary text-white" })
        </div>
    </div>
</div>}